stages:
  - build-img
  - build
  - deploy

docker build:
  stage: build-img
  image:
    name: img.doom.fm/internal/docker-build
  script:
    - sh /usr/local/bin/build-image
  rules:
    - changes:
      - Dockerfile

resume:
  stage: build
  image:
    name: "img.doom.fm/agargiulo/resume:${CI_COMMIT_REF_NAME}"
  script:
    - which pdflatex
