stages:
  - build-img
  - build
  - deploy

docker build:
  stage: build-img
  image:
    name: img.doom.fm/internal/docker-build
  script:
    - sh /usr/local/bin/build-image
  rules:
    - changes:
      - Dockerfile

resume:
  stage: build
  image:
    name: "img.doom.fm/agargiulo/resume:${CI_COMMIT_REF_NAME}"
  script:
    - pdflatex resume.tex
    - pygmentize -f html -O full,style=colorful,linenos=1 -l latex -o resume.tex.html resume.tex
  artifacts:
    name: resume
    paths:
      - resume.pdf
      - resume.tex.html
      - resume.tex

deploy3:
  stage: deploy
  image:
    name: "img.doom.fm/agargiulo/resume:${CI_COMMIT_REF_NAME}"
  variables:
    GIT_STRATEGY: none
  script:
    - ls -la
  dependencies:
    - resume
